import { initDatabase } from "@/shared/infrastructure/database"

import { container } from "./container"
import { runMigrationsIfAvailable } from "./migration-runner"
import { createQueryClient } from "./query-client"
import registerInfrastructure from "./register-infrastructure"
import SqliteSyncEngine from "../shared/infrastructure/sqlite-sync-engine"

export const queryClient = createQueryClient()

export async function initAppBootstrap(): Promise<void> {
  console.debug("BOOTSTRAP: initAppBootstrap() starting")
  // initialize database and register it in the singleton container
  const db = await initDatabase()
  console.debug("BOOTSTRAP: initDatabase() finished")

  // attempt to run SQL migrations generated by drizzle in dev/node
  await runMigrationsIfAvailable(db)
  console.debug("BOOTSTRAP: runMigrationsIfAvailable() finished")

  try {
    container.register("database", db)
    // register concrete infrastructure implementations that depend on the DB
    registerInfrastructure(db)
    console.debug("BOOTSTRAP: registerInfrastructure done")

    // register a minimal sqlite-backed SyncEngine for local outbox flushing
    try {
      const sync = new SqliteSyncEngine(db)
      container.register("syncEngine", sync)
      console.debug("BOOTSTRAP: syncEngine registered")
    } catch (err) {
      console.error("BOOTSTRAP: failed to register syncEngine", err)
      // ignore if registration fails in early dev
    }
  } catch (err) {
    console.error("BOOTSTRAP: container/register errors", err)
    // ignore registration errors in early development
  }
}

export default {
  queryClient,
  init: initAppBootstrap,
}
